### ISSUE TITLE
Merge parameters by level

### ISSUE THREAD

**Issue by olgapeled** [tr11/python-configuration#14]
So, that means that there is no way to define the level by which the merge will happen?
thank you!
 
> If the 2 files have the same nested parameter (for example a dictionary). Is there a way that the first definition will override the second one without the merge of the inner items.
"The hierarchy works the other way around; the first file is 1 so any parameter existing in 1 will not be searched in file 2."
Means that the search will be ONLY by level 1 ?
For example:
1.py:
d = { "1" : 1}
2.py:
d = {"2" : 2}

> By design, internally the definitions are converted to a single dictionary with keys such as a.b.c. In the case above, the keys are indeed merged and the configuration becomes
{'d.2': 2, 'd.1': 1}
In particular, when you retrieve d, the result will be {'2': 2, '1': 1}. You can also get d.1 and d.2 or even 1 and 2 from the result of d.

**Comment by tr11** [comment]
Right now, there's not. This library was intended to do the opposite of what you described; we wanted a way to "overlay" a few configurations tweaks without overwriting any of the unrelated parameters.

I need to take a closer look to see if this is even possible without rewriting the whole library.  There are a few internal methods that need the structure I described above.

In the meantime, if you need to do something like this, you can just change your files to read: 
1.py:
```
from collections import UserDict
d = UserDict({ "1" : 1})
```

2.py:
```
from collections import UserDict
d = UserDict({ "2" : 2})
```

The resulting config will not merge the dictionaries since the `UserDict` class is not a subclass of `dict`. Not ideal, but should work.

**Comment by olgapeled** [comment]
Thank you!

I want to use it only on specific parameters!
Thank you !!!

**Comment by tr11** [comment]
No problem!  I added a note to the readme to mention the default behavior in this issue.
